import type { Courses } from '@/types/course';

export const courses: Courses = [
  {
    categories: [
      { id: 1, name: 'Blockchain' },
      { id: 2, name: 'Beginner' },
    ],
    description: 'Learn the basics of blockchain technology and distributed ledgers.',
    id: 1,
    image: null,
    rating: 4.5,
    students: 1200,
    title: 'Blockchain Fundamentals',
    wishlist: false,
  },
  {
    categories: [
      { id: 3, name: 'Smart Contract' },
      { id: 4, name: 'Ethereum' },
    ],
    description: 'Hands-on guide to building smart contracts with Solidity.',
    id: 2,
    image: null,
    rating: 4.7,
    students: 950,
    title: 'Smart Contract Development',
    wishlist: true,
  },
  {
    categories: [
      { id: 5, name: 'Web3' },
      { id: 2, name: 'Beginner' },
    ],
    description: 'Introduction to wallets, dApps, and the decentralized web.',
    id: 3,
    image: null,
    rating: 4.2,
    students: 800,
    title: 'Web3 for Beginners',
    wishlist: false,
  },
  {
    categories: [
      { id: 6, name: 'DeFi' },
      { id: 7, name: 'Finance' },
    ],
    description: 'Explore DeFi apps, yield farming, and liquidity pools.',
    id: 4,
    image: null,
    rating: 4.6,
    students: 1100,
    title: 'Decentralized Finance (DeFi) Essentials',
    wishlist: true,
  },
  {
    categories: [
      { id: 8, name: 'NFT' },
      { id: 9, name: 'Digital Assets' },
    ],
    description: 'Understand NFTs, marketplaces, and tokenized art.',
    id: 5,
    image: null,
    rating: 4.3,
    students: 750,
    title: 'NFTs & Digital Assets',
    wishlist: false,
  },
  {
    categories: [
      { id: 4, name: 'Ethereum' },
      { id: 1, name: 'Blockchain' },
    ],
    description: 'A technical breakdown of Ethereum’s architecture and ecosystem.',
    id: 6,
    image: null,
    rating: 4.8,
    students: 1400,
    title: 'Ethereum Deep Dive',
    wishlist: true,
  },
  {
    categories: [
      { id: 10, name: 'Solana' },
      { id: 11, name: 'Development' },
    ],
    description: 'Learn to build fast dApps on the Solana blockchain.',
    id: 7,
    image: null,
    rating: 4.4,
    students: 680,
    title: 'Solana Development Bootcamp',
    wishlist: false,
  },
  {
    categories: [
      { id: 12, name: 'Security' },
      { id: 13, name: 'Best Practices' },
    ],
    description: 'Secure wallets, avoid scams, and protect your assets.',
    id: 8,
    image: null,
    rating: 4.7,
    students: 990,
    title: 'Crypto Security & Best Practices',
    wishlist: true,
  },
  {
    categories: [
      { id: 14, name: 'DAO' },
      { id: 15, name: 'Governance' },
    ],
    description: 'Dive into decentralized organizations and decision-making.',
    id: 9,
    image: null,
    rating: 4.1,
    students: 540,
    title: 'DAOs & Governance',
    wishlist: false,
  },
  {
    categories: [
      { id: 5, name: 'Web3' },
      { id: 16, name: 'Frontend' },
      { id: 17, name: 'React' },
    ],
    description: 'Connect React apps to blockchain using Web3 libraries.',
    id: 10,
    image: null,
    rating: 4.6,
    students: 860,
    title: 'Web3 Frontend with React & Ethers.js',
    wishlist: true,
  },
  {
    categories: [
      { id: 18, name: 'Tokenomics' },
      { id: 19, name: 'Economics' },
    ],
    description: 'Explore how crypto projects design sustainable token systems.',
    id: 11,
    image: null,
    rating: 4.5,
    students: 730,
    title: 'Tokenomics & Crypto Economics',
    wishlist: false,
  },
  {
    categories: [
      { id: 20, name: 'Layer 2' },
      { id: 21, name: 'Scaling' },
    ],
    description: 'Understand Optimism, Arbitrum, and zk-rollups for faster dApps.',
    id: 12,
    image: null,
    rating: 4.7,
    students: 1020,
    title: 'Layer 2 Scaling Solutions',
    wishlist: true,
  },
];
